### ISSUE TITLE
傻狗玩意

### ISSUE THREAD

**Issue by illaoiiiii** [laterdayi/tests#1]
咋了是不是你叫别人用这个啊，文档文档稀烂，示例示例没有，就只有猜，别人新手永不会骂别人才，这不是框架问题，你那么牛逼就别用框架，全给老子用手写知道吗废物，要不就别叫

**Comment by laterdayi** [comment]
小菜比，就该不让你会

**Comment by laterdayi** [comment]
急死你， 小菜比

**Comment by laterdayi** [comment]
菜狗被骂不应该 ？

**Comment by laterdayi** [comment]
让你麻来 都比你聪明

**Comment by laterdayi** [comment]
写HTML 会吗 ？ 不会我给你推荐菜鸟教程

**Comment by laterdayi** [comment]
说前端无门槛 就是你这种菜比，来混，哎。

**Comment by illaoiiiii** [comment]
咋了说难用你急了？说了你很牛逼就手写，不用框架，你很牛吗，写个组件发上来啊，废物，菜鸟教程，也只有你这种彩笔还看那玩意，我急了，我没急了哦，用element能实现咋了，用不来这框家咋了

**Comment by laterdayi** [comment]
小菜比 不会用 急了急了

**Comment by laterdayi** [comment]
这东西不是牵条狗都知道咋用 ？

**Comment by laterdayi** [comment]
还真有人不会用组件， 急死了急死了

**Comment by laterdayi** [comment]
@illaoiiiii    不会用 不回家养猪 ？  小猪仔

**Comment by laterdayi** [comment]
@illaoiiiii  小土狗字都能打错， 你是小结巴吧  ？

**Comment by illaoiiiii** [comment]
咋的了，外包程序给你干的牛逼的不得了了，会用咋了，你能上天，给你牛逼的啊，我用element能实现，为啥要找罪受呢，我现在换个项目不用这个框架了。先说下我不只写前端哦，废物，爷之前写后端的

**Comment by illaoiiiii** [comment]
真的，会用就是高人一等，真的是人上人哦，太牛逼啦

**Comment by laterdayi** [comment]
菜狗， 月薪多少，可惜你die全栈哦， 难受死了

**Comment by illaoiiiii** [comment]
厉害厉害会个node就是全栈

**Comment by laterdayi** [comment]
就你这种，写啥都写不明白的货色

**Comment by illaoiiiii** [comment]
给你牛逼坏了啊

**Comment by laterdayi** [comment]
可惜你die 数据库 跨平台 后台 前台 都会 难受死了

**Comment by laterdayi** [comment]
后台写个前台就不会了 ？

**Comment by illaoiiiii** [comment]
所以说嘛，啥都干就是外包，或者小公司哦

**Comment by laterdayi** [comment]
急死了 月薪12K的小东西

**Comment by illaoiiiii** [comment]
哎，懒得说你了哦

**Comment by illaoiiiii** [comment]
外包真的给你干的牛逼坏了

**Comment by laterdayi** [comment]
搞笑， 全栈和外包都分不清

**Comment by laterdayi** [comment]
你可真逗  github 0贡献，秀死了

**Comment by illaoiiiii** [comment]
呵呵，我见过啥都干的只有外包和小公司了

**Comment by illaoiiiii** [comment]
所以你呢，你的贡献呢

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/6295c844-47ee-4768-a024-221b01657bef)
  看看你die再看看你

**Comment by laterdayi** [comment]
小菜比， 你可别说了， 我都懒得搭理你

**Comment by illaoiiiii** [comment]
有这个有啥用哦，我平时写代码都不开这个

**Comment by illaoiiiii** [comment]
每天输出你那垃圾代码，贴个图也叫牛逼？

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/2e530417-9dc4-498b-a4ef-448c79a25b16)
该不会有人是伸手党吧 ？

**Comment by laterdayi** [comment]
是不是一个PR 都不提 ？

**Comment by laterdayi** [comment]
你知道啥叫PR不，，，， 你知道咋提吗 ？

**Comment by illaoiiiii** [comment]
哦，怪不得，是给这个垃圾框架贡献啊，那没事了

**Comment by illaoiiiii** [comment]
写了这么久这框架还是bug一堆你有脸

**Comment by laterdayi** [comment]
不好意思哦， 你die，vue  vueuse create vue  ，vue dx 都贡献， 很难受

**Comment by illaoiiiii** [comment]
真的好有脸啊，天天写垃圾代码，隔着装逼

**Comment by illaoiiiii** [comment]
我找你伸手，搞笑，说了不是公司哪个垃圾项目，狗都不用这框架

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/6df942aa-0b52-4df5-81fd-c808d06edaf5)
伸手党  啥都不会用，急死了 急死了

**Comment by illaoiiiii** [comment]
我猜给这个框架提东西的，不会都是狗把

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/6df942aa-0b52-4df5-81fd-c808d06edaf5)
伸手党  啥都不会用，急死了 急死了

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/6df942aa-0b52-4df5-81fd-c808d06edaf5)
满屏空白 不会今年才知道github刚注册的吧 
伸手党  啥都不会用，急死了 急死了

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/6df942aa-0b52-4df5-81fd-c808d06edaf5)
满屏空白 不会今年才知道github刚注册的吧 
伸手党  啥都不会用，急死了 急死了 ，别说代码了， 养猪你都不如猪聪明。

**Comment by illaoiiiii** [comment]
对不起哦，早就注册了，只是写的项目不传自己git而已

**Comment by laterdayi** [comment]
![图片](https://github.com/laterdayi/tests/assets/122137647/6df942aa-0b52-4df5-81fd-c808d06edaf5)
满屏空白 不会今年才知道github刚注册的吧 
伸手党  啥都不会用，急死了 急死了 ，别说代码了， 养猪你都不如猪聪明。

**Comment by laterdayi** [comment]
笑死了， 自己啥时候注册的 不知道？

**Comment by laterdayi** [comment]
你以为github看不出来 ？

**Comment by illaoiiiii** [comment]
哎，别逼逼了，这框架写了这么九还是一坨屎

**Comment by illaoiiiii** [comment]
哎，你牛逼就完了，会用牛逼上天了

**Comment by laterdayi** [comment]
2021还是2020注册的  小朋友 ？

**Comment by laterdayi** [comment]
刚毕业吧

**Comment by laterdayi** [comment]
玩王者荣耀的吧 ？

**Comment by illaoiiiii** [comment]
你估计玩原神我感觉，一股op味，✌这俩都不玩哦，✌玩lol，废物

**Comment by illaoiiiii** [comment]
你这逼号2023年才注册的吧，废物

**Comment by illaoiiiii** [comment]
原来是不敢啊，怪不得，整天给垃圾框架提代码刷无聊kpi真的无聊到死了吧

**Comment by laterdayi** [comment]
就你这猪脑子

**Comment by laterdayi** [comment]
搞笑死了

**Comment by illaoiiiii** [comment]
不是吗，废物

**Comment by laterdayi** [comment]
就你这猪脑子， 养猪都不配。猪都比你聪明

**Comment by laterdayi** [comment]
不跟你说了哦， 工作三年 ，工资过12K吗 ？  懒得跟你说了， 浪费我时间， 886  ，走哪都是小菜比

**Comment by illaoiiiii** [comment]
哎，给你牛逼的，等你那天不用ui自己手写再来说别人笨

**Comment by laterdayi** [comment]
哪个语言你都学不明白，再见

**Comment by illaoiiiii** [comment]
比你只会个node就说是全栈的厉害

**Comment by laterdayi** [comment]
可惜咯， 你die啥都会，难受不， 工资还高， 急死咯

**Comment by laterdayi** [comment]
你说咋办 工资高 ？

**Comment by laterdayi** [comment]
你慢慢在这急哦， 加油，可以的，天天工作中挨骂吧，小菜比 被骂正常的 心态要好

**Comment by illaoiiiii** [comment]
工资1w，但是✌不在一线

**Comment by illaoiiiii** [comment]
无所谓，没人骂我，我说不会别人给我换项目了

**Comment by laterdayi** [comment]
原来你die我比你多几倍，拉倒吧。。。赶紧滚。 你配吗

**Comment by illaoiiiii** [comment]
你工资高不是给这垃圾框架替代吗刷上去的?

**Comment by laterdayi** [comment]
我说你是啥货色 1W 你可别恶心我了， 快滚。。 小货色一个。

**Comment by illaoiiiii** [comment]
菜鸡，就凭你干的早，给你牛逼坏了

**Comment by laterdayi** [comment]
@illaoiiiii    土狗 不错  上推了
![图片](https://github.com/laterdayi/tests/assets/122137647/99bc6bc1-f7ee-41cc-b90c-530e4f506221)

**Comment by laterdayi** [comment]
@illaoiiiii   拉吉都不重写  是不会吗 ？
![图片](https://github.com/laterdayi/tests/assets/122137647/7a0315dc-e5ea-4b84-b4e0-fea181e753df)

**Comment by laterdayi** [comment]
@illaoiiiii  土狗 说话， 今天给你爹报道了吗 ？

**Comment by illaoiiiii** [comment]
啊，就几个人回复就在这叫啊，我可真成了大明星了哎，不是你这垃圾框架不是公司非要用，谁用哦，只能说选这个框架的同事错信你了哎，我不是说了吗，公司非要用，不是公司用你爹我绝对不用，懂了吗，伸手党？你那破壁功能还用伸手，直接魔改antd或element就好了呢

**Comment by laterdayi** [comment]
> i

土狗 说话， 今天给你爹报道了吗 ？

**Comment by illaoiiiii** [comment]
只会骂人了呗，逻辑都没有了，情绪输出罢了。

**Comment by laterdayi** [comment]
笑死了，我不会 我急死了， 只会情绪输出 ， 不会写哦

**Comment by laterdayi** [comment]
> 只会骂人了呗，逻辑都没有了，情绪输出罢了。

怎么办，文档看不懂，不会写， 我要情绪输出啦， 急死了 急死了 嘻嘻

**Comment by illaoiiiii** [comment]
你自己看看你那个issue，是我一个人这么说嘛，一堆人这么说，怎么眼睛瞎了看不见，bug一堆不知道？

**Comment by laterdayi** [comment]
> 你自己看看你那个issue，是我一个人这么说嘛，一堆人这么说，怎么眼睛瞎了看不见，bug一堆不知道？

fk you mother

**Comment by illaoiiiii** [comment]
![image](https://github.com/laterdayi/tests/assets/73126812/484b4e66-492d-4b61-8bf0-7127580a71aa)
自己看一堆东西有问题

**Comment by laterdayi** [comment]
![image](https://github.com/laterdayi/tests/assets/122137647/80cb60a7-bb7a-44bf-accb-c25e2da6a7f9)
我看你吗的头看， 煞笔

**Comment by laterdayi** [comment]
![image](https://github.com/laterdayi/tests/assets/122137647/d6160509-1f2d-4d33-a56d-dd47f2ac8d8d)

看你吗 菜比

**Comment by laterdayi** [comment]
![image](https://github.com/laterdayi/tests/assets/122137647/3e4cd6fd-51ad-4b7e-96fa-87eb4aaa3a0f)
看啥 看你的爹 ？  野种

**Comment by illaoiiiii** [comment]
15k没办法，等你到90k的时候估计issue起码2k吧，垃圾框架

**Comment by illaoiiiii** [comment]
flutter? 这玩意本来就问题多啊，也就你这种菜逼用了哦，咸鱼用这玩意写出来一堆bug，还好意思截图。

**Comment by laterdayi** [comment]
> 15k没办法，等你到90k的时候估计issue起码2k吧，垃圾框架

用你吗 ？  土狗

**Comment by laterdayi** [comment]
> flutter? 这玩意本来就问题多啊，也就你这种菜逼用了哦，咸鱼用这玩意写出来一堆bug，还好意思截图。

笑死了， 凑你吗， 用 RN  Uniapp ？  嘻嘻嘻嘻  乐

**Comment by laterdayi** [comment]
> flutter? 这玩意本来就问题多啊，也就你这种菜逼用了哦，咸鱼用这玩意写出来一堆bug，还好意思截图。

该不会你这种土狗 啥也不会吧。 笑死了 html js 入门 ？

**Comment by laterdayi** [comment]
> flutter? 这玩意本来就问题多啊，也就你这种菜逼用了哦，咸鱼用这玩意写出来一堆bug，还好意思截图。

你能玩明白啥， 菜比 笑死了  要啥没啥 跟你爹娘一样

**Comment by laterdayi** [comment]
> flutter? 这玩意本来就问题多啊，也就你这种菜逼用了哦，咸鱼用这玩意写出来一堆bug，还好意思截图。

笑死了 还用 RN 呢， 丢人吗， 还看 RN 学习资料笑死了

**Comment by laterdayi** [comment]
> flutter? 这玩意本来就问题多啊，也就你这种菜逼用了哦，咸鱼用这玩意写出来一堆bug，还好意思截图。

fluter 不把你 RN 吊起来锤 ？ 笑死了  土狗， 一个 js 都玩不明白就别玩别的了 写写 uniapp RN 挺好的 🤒 🤒 🤒

**Comment by laterdayi** [comment]
![image](https://github.com/laterdayi/tests/assets/122137647/e176ccc7-e490-49bc-b20b-07f8417582d9)
d丢死人了， 推特一堆人看笑话  乐

**Comment by laterdayi** [comment]
![image](https://github.com/laterdayi/tests/assets/122137647/ae04a9ae-c93d-4a80-a6f5-b56eaa0aab18)
嘻嘻

**Comment by illaoiiiii** [comment]
RN确实用过，后来觉得不好用，只能写一点玩具项目罢了。Uniapp你爹我还真不用，别在这瞎猜。还有我说的有错吗，天天放你这清朝老图，是不是比不过Antd，戳到你痛处了吧，小丑。

**Comment by laterdayi** [comment]
> RN确实用过，后来觉得不好用，只能写一点玩具项目罢了。Uniapp你爹我还真不用，别在这瞎猜。还有我说的有错吗，天天放你这清朝老图，是不是比不过Antd，戳到你痛处了吧，小丑。

那用你吗 ？ 除了 flutter 还有你吗 ？野种

**Comment by laterdayi** [comment]
> RN确实用过，后来觉得不好用，只能写一点玩具项目罢了。Uniapp你爹我还真不用，别在这瞎猜。还有我说的有错吗，天天放你这清朝老图，是不是比不过Antd，戳到你痛处了吧，小丑。

比不过你还用， 你是不是贱种， 跟你吗一样

**Comment by illaoiiiii** [comment]
我不用了啊，就用过一个项目，给你爹恶心坏了

**Comment by laterdayi** [comment]
> RN确实用过，后来觉得不好用，只能写一点玩具项目罢了。Uniapp你爹我还真不用，别在这瞎猜。还有我说的有错吗，天天放你这清朝老图，是不是比不过Antd，戳到你痛处了吧，小丑。

要不你自己写一个， 还老图， 下面评论区老热闹了 靠你娘   不会用还用，犟种一个

**Comment by illaoiiiii** [comment]
不是你在这狂吠，不知道在这叫啥

**Comment by laterdayi** [comment]
> 我不用了啊，就用过一个项目，给你爹恶心坏了

笑死了 可惜好多开源在用 ， 没辙  ，都会用  就你不会 嘻嘻 该

**Comment by illaoiiiii** [comment]
是啊，没办法我平时工作Antd会用，会魔改就完了

**Comment by laterdayi** [comment]
> 不是你在这狂吠，不知道在这叫啥

你这种菜比 到哪都一样

**Comment by illaoiiiii** [comment]
还真用不到你这玩意

**Comment by laterdayi** [comment]
> 是啊，没办法我平时工作Antd会用，会魔改就完了

跟你娘一样，野种，没脑子

**Comment by laterdayi** [comment]
你看见你吗那笨比样， 你不把她吊起来造  ？

**Comment by laterdayi** [comment]
> 还真用不到你这玩意

啥都用不明白的东西

**Comment by laterdayi** [comment]
> RN确实用过，后来觉得不好用，只能写一点玩具项目罢了。Uniapp你爹我还真不用，别在这瞎猜。还有我说的有错吗，天天放你这清朝老图，是不是比不过Antd，戳到你痛处了吧，小丑。

怎么不说话了 曹你吗 笨比

**Comment by illaoiiiii** [comment]
急了，就喜欢看你这条狗急

**Comment by illaoiiiii** [comment]
怎么不回话了，小狗，不会噶了吧

**Comment by illaoiiiii** [comment]
不会是人没了吧，怎么不叫了
